parameters:

services:
  meyfarth.listener.entity_logger_listener:
    class: Meyfarth\EntityLoggerBundle\EventListener\EntityLoggerListener
    arguments:
        container: @service_container
    tags:
      - { name: doctrine.event_listener, event: onFlush }
      - { name: doctrine.event_listener, event: postPersist }

  meyfarth.subscriber.dynamic_user_subscriber:
    class: Meyfarth\EntityLoggerBundle\EventListener\DynamicUserMappingSubscriber
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata }

  meyfarth.service.log_service:
    class: Meyfarth\EntityLoggerBundle\Service\EntityLoggerService
