Meyfarth\EntityLoggerBundle\Entity\EntityLog:
    type: entity
    table: meyfarth_entity_log
    repositoryClass: Meyfarth\EntityLoggerBundle\Repository\EntityLogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        entity:
            type: string
            length: 255
        foreignId:
            type: array
            column: foreign_id
        data:
            type: array
        typeLog:
            type: smallint
            unsigned: true
            column: type_log
    lifecycleCallbacks: {  }
